### ISSUE TITLE
Cannot save timezone created_at and updated_at

### ISSUE THREAD

**Issue by ericksuryadinata** [Rocketseat/adonis-timezone#3]
Eg. 
`created_at` and `updated_at` from this package is `"2020-01-07 17:09:07"` 
Timezone set to `Asia/Jakarta`

My vps machine use `America/New_York` timezone, and of course MySql will use this as the timezone

so whenever I save my record to database, it will automatically change to `America/New_York` not my current settings with this package `Asia/Jakarta`

so the example given in above, database will save it to
`created_at` =  `"2020-01-07 05:09:07"`
`updated_at` =  `"2020-01-07 05:09:07"`

any step that i'm missing ? please some advice

thanks in advance

ps : I know I can change my vps timezone, but I avoid this way since in my database already has too much record

**Comment by HigoRibeiro** [comment]
Hi @ericksuryadinata !

Actually this provider will read your `datetime` from the database and apply the timezone that you set for it.
To reach an expected result, you need to set the `datetime` of the database to be saved in UTC.

On **node** you can set the timezone in UTC through `.env` by setting `TZ=UTC`.

**Comment by ericksuryadinata** [comment]
added my `.env` `TZ=Asia/Jakarta` solved my problem, 

I think it should add in documentation

thanks in advance
